services:
  postgres-db:
    image: postgres:15-alpine
    container_name: inventario_bd
    restart: always
    environment:
      POSTGRES_USER: user_inventario
      POSTGRES_PASSWORD: password_seguro
      POSTGRES_DB: inventario_db
      command: postgres -c listen_addresses='*'

    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  reportes-app:
    build: ./reportes # <-- Apunta directamente a la carpeta
    container_name: inventario_node
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=postgres-db
      - DB_USER=user_inventario
      - DB_PASS=password_seguro
      - DB_NAME=inventario_db
    depends_on:
      - postgres-db

volumes:
  pg_data: